#! /usr/bin/env ruby
#
  host = ENV.fetch('HOST'){ '0.0.0.0' }
  port = ENV.fetch('PORT'){ '4242' }

  cmd = "./bin/rackup --host #{ host } --port #{ port }"

#
  @pid =
    nil

  Thread.new do
    loop do
      @pid = Process.spawn(cmd)
      Process.wait @pid
      @pid = nil
      sleep rand
    end
  end

  Listen.to '.' do
    #Process.kill('USR2', @pid)
    #Process.kill('INT', @pid)
  end.start

  sleep

#
  BEGIN {
    Dir.chdir(File.dirname(File.dirname(__FILE__)))

    require 'bundler/setup'

    require 'listen'
  }
