#! /usr/bin/env sh

# 2015  echo 'net.ipv4.ip_unprivileged_port_start=0' > /etc/sysctl.d/50-unprivileged-ports.conf
# 2016  sudo echo 'net.ipv4.ip_unprivileged_port_start=0' > /etc/sysctl.d/50-unprivileged-ports.conf

# https://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-on-linux

# https://caddyserver.com/docs/install#debian-ubuntu-raspbian
sudo $(which caddy) reverse-proxy --from drawohara.dev --to :4242

#ngrok http 4242


# >>> Welcome to Webi! - modern tools, instant installs.  <<<
#     We expect your experience to be absolutely perfect!
#
#     Success? Star it!   https://github.com/webinstall/webi-installers
#     Problem? Report it: https://github.com/webinstall/webi-installers/issues
#                         (your system is GNU/Linux/x86_64 with libc & curl+wget)
#
# Bootstrapping Webi
#     Downloading https://webi.sh/packages/webi/webi.sh
#         to ~/.local/bin/webi
#     Running ~/.local/bin/webi caddy@stable
#
# Installing caddy ...
#     Found  ~/.local/bin
#     Initializing ~/.config/envman/
#     Edit ~/.profile to source ~/.config/envman/load.sh
#     Edit ~/.bashrc to source ~/.config/envman/load.sh
#     Edit ~/.zshrc to source ~/.config/envman/load.sh
#     Downloading caddy from
#       https://github.com/caddyserver/caddy/releases/download/v2.9.0/caddy_2.9.0_linux_amd64.tar.gz
#     Saved as ~/Downloads/webi/caddy/2.9.0/caddy_2.9.0_linux_amd64.tar.gz
#     Extracting ~/Downloads/webi/caddy/2.9.0/caddy_2.9.0_linux_amd64.tar.gz
#     Installing to ~/.local/opt/caddy-v2.9.0/bin/caddy
#
#     Installed 'caddy v2.9.0' as ~/.local/bin/caddy
#
#     Edit ~/.config/envman/PATH.env to add:
#         ~/.local/bin
#
# >>> ACTION REQUIRED <<<
#         Copy, paste & run the following command:
#         source ~/.config/envman/PATH.env
#         (newly opened terminal windows will update automatically)
